package learn.solarpanels.model;

public enum SolarPanelMaterial {
    MULTICRYSTALLINE_SILICON,
    MONOCRYSTALLINE_SILICON,
    AMORPHUS_SILICON,
    CADMIUM_TELLURIDE,
    COPPER_INDIUM_GALLIUM_SELENIDE
}
